const actionTypes = Object.freeze({
    //Product
    GET_ALL_PRODUCT_SUCCESS: 'GET_ALL_PRODUCT_SUCCESS',
    GET_ALL_PRODUCT_FAIL: 'GET_ALL_PRODUCT_FAIL',
    GET_SINGLE_PRODUCT_SUCCESS: 'GET_SINGLE_PRODUCT_SUCCESS',
    GET_SINGLE_PRODUCT_FAIL: 'GET_SINGLE_PRODUCT_FAIL'
});

export default actionTypes;
